name: Bibliography

on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # setup the repository
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4

      - run: |
          python src/create_bibliography.py
          git config user.email "panahiparham@gmail.com"
          git config user.name "Parham Mohammad Panahi"
          git add docs/publications.bib
          git commit -m "ci: updated bibliography"
          git push origin main

